{% set name = "uharfbuzz" %}
{% set version = "0.37.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/uharfbuzz-{{ version }}.zip
  sha256: df8bee4a05e52fc7d4ed8a9162f68752c2c11e62c1ae91d7b77abdd5f786938a

build:
  script: {{ PYTHON }} -m pip install . -vv
  number: 0
  # Compile error on Mac OS X: harfbuzz/src/hb-shape.cc:158:5: - too many arguments provided to function-like macro invocation
  skip: true  # [osx]

requirements:
  build:
    - {{ compiler('cxx') }}
    - cython
  host:
    - pip
    - python
    - setuptools-scm
    - cython
  run:
    - python

test:
  imports:
    - uharfbuzz
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/trufont/uharfbuzz
  summary: Streamlined Cython bindings for the harfbuzz shaping engine
  license: Apache-2.0
  license_file:
    - LICENSE

extra:
  recipe-maintainers:
    - jan-janssen
